title: Emoji frame
description: Your text deserves to be placed in an emoji frame
url: http://katydecorah.com
baseurl: /emoji-frame
twitter: katydecorah
author: katydecorah
twitter:
  username: katydecorah
image: image/site.png
gems:
  - jekyll-seo-tag

exclude:
  - README.md
  - node_modules
  - *.lock
  - package.json